# Generated by Django 5.0.2 on 2024-09-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagram", "0002_alter_diagram_id_alter_diagram_system_and_more"),
        ("metadata", "0007_interface_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="rel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadata.relation"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="cls",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadata.classifier"
            ),
        ),
    ]
