# Generated by Django 5.0.2 on 2026-09-18 13:16

import django.db.models.deletion
import metadata.models.fields
import metadata.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("signal", "Signal"),
                            ("enum", "Enum"),
                            ("interface", "Interface"),
                            ("usecase", "Usecase"),
                            ("actor", "Actor"),
                            ("systemboundary", "System Boundary"),
                            ("swimlane", "Swimlane"),
                            ("action", "Action"),
                            ("decision", "Decision"),
                            ("final", "Final"),
                            ("fork", "Fork"),
                            ("initial", "Initial"),
                            ("join", "Join"),
                            ("merge", "Merge"),
                            ("object", "Object"),
                            ("event", "Event"),
                            ("system", "System"),
                            ("container", "Container"),
                            ("component", "Component"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("association", "Association"),
                            ("generalization", "Generalization"),
                            ("composition", "Composition"),
                            ("dependency", "Dependency"),
                            ("controlflow", "Controlflow"),
                            ("interaction", "Interaction"),
                            ("extension", "Extension"),
                            ("inclusion", "Inclusion"),
                            ("interface", "Interface"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="metadata.classifier",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="metadata.classifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndpointLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("target", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Enum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("radius", models.PositiveIntegerField(default=0)),
                ("text_color", models.CharField(default="#000000", max_length=7)),
                ("accent_color", models.CharField(default="#F5F5F4", max_length=7)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("abstract", "Abstract"),
                            ("basic", "Basic"),
                            ("modern", "Modern"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                ("manager_access", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Multiplicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_lower", models.PositiveIntegerField()),
                ("source_upper", models.PositiveIntegerField(blank=True, null=True)),
                ("target_lower", models.PositiveIntegerField()),
                ("target_upper", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_automatic", models.BooleanField(default=False)),
                (
                    "custom_code",
                    metadata.models.fields.PythonField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(metadata.models.utils.ValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassClassifier",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Final",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                (
                    "activity_scope",
                    models.CharField(
                        choices=[("flow", "Flow"), ("activity", "Activity")],
                        default="activity",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Initial",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("scheduled", models.BooleanField(default=False)),
                (
                    "schedule",
                    metadata.models.fields.CronField(
                        blank=True, default="", max_length=100
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterfaceClassifier",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemClassifier",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.relation",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Int"),
                            ("bool", "Bool"),
                            ("datetime", "Datetime"),
                            ("enum", "Enum"),
                        ],
                        max_length=16,
                    ),
                ),
                ("derived", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("body", metadata.models.fields.PythonField(blank=True, null=True)),
                (
                    "enum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributes",
                        to="metadata.enum",
                    ),
                ),
                (
                    "uml_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="metadata.classclassifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnumLiteral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "enum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literals",
                        to="metadata.enum",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="metadata.interface",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("activity", "Activity")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="metadata.category",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="metadata.interface",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="metadata.action",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("text", models.CharField(blank=True, default="", max_length=255)),
                ("allow_create", models.BooleanField(default=False)),
                ("allow_update", models.BooleanField(default=False)),
                ("allow_delete", models.BooleanField(default=False)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="metadata.interface",
                    ),
                ),
                (
                    "uml_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_components",
                        to="metadata.classclassifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_attributes",
                        to="metadata.attribute",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="metadata.sectioncomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_sections",
                        to="metadata.page",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_sections",
                        to="metadata.sectioncomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="metadata.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relation",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="metadata.system",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interfaces",
                to="metadata.system",
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.system",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interfaces",
                to="metadata.actor",
            ),
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Int"),
                            ("bool", "Bool"),
                            ("datetime", "Datetime"),
                            ("enum", "Enum"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", metadata.models.fields.PythonField(blank=True, null=True)),
                (
                    "uml_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="metadata.classclassifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uml_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objects",
                        to="metadata.classclassifier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="metadata.signal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Swimlane",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swimlanes",
                        to="metadata.actor",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_swimlanes",
                        to="metadata.classifier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="metadata.swimlane",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(metadata.models.utils.ValidationMixin, models.Model),
        ),
        migrations.AddField(
            model_name="action",
            name="swimlane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="metadata.swimlane",
            ),
        ),
        migrations.CreateModel(
            name="SystemBoundary",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_boundaries",
                        to="metadata.system",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="boundary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actors",
                to="metadata.systemboundary",
            ),
        ),
        migrations.CreateModel(
            name="Usecase",
            fields=[
                (
                    "classifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.classifier",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "boundary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usecases",
                        to="metadata.systemboundary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.relation",
                    ),
                ),
                ("derived", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "labels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association",
                        to="metadata.endpointlabel",
                    ),
                ),
                (
                    "multiplicity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association",
                        to="metadata.multiplicity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.relation",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "labels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition",
                        to="metadata.endpointlabel",
                    ),
                ),
                (
                    "multiplicity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition",
                        to="metadata.multiplicity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ControlFlow",
            fields=[
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.relation",
                    ),
                ),
                ("guard", models.CharField(blank=True, default="", max_length=255)),
                ("weight", models.FloatField(blank=True, default=None, null=True)),
                ("is_else", models.BooleanField(default=False)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("==", "Equal"),
                            ("!=", "Not Equal"),
                            (">", "Greater Than"),
                            ("<", "Less Than"),
                            (">=", "Greater Than Or Equal"),
                            ("<=", "Less Than Or Equal"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "aggregator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("avg", "Avg"),
                            ("min", "Min"),
                            ("max", "Max"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "comparison_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_flows",
                        to="metadata.attribute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterfaceRelation",
            fields=[
                (
                    "relation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(class)s",
                        serialize=False,
                        to="metadata.relation",
                    ),
                ),
                (
                    "provided",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_interfaces",
                        to="metadata.interface",
                    ),
                ),
                (
                    "required",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="required_interfaces",
                        to="metadata.interface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="sectionattribute",
            constraint=models.UniqueConstraint(
                fields=("section", "order"), name="unique_section_attribute_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionattribute",
            constraint=models.UniqueConstraint(
                fields=("section", "attribute"), name="unique_section_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.UniqueConstraint(
                fields=("page", "order"), name="unique_page_section_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.UniqueConstraint(
                fields=("page", "section"), name="unique_page_section"
            ),
        ),
    ]
