# Generated by Django 5.0.1 on 2024-01-29 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


def set_relation_defaults(apps, schema_editor):
    Relations = apps.get_model("metadata", "Relation")
    for relation in Relations.objects.all():
        relation.system = relation.source.system
        relation.save()


def reverse_func(*_, **__):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="metadata.system",
            ),
        ),
        migrations.RunPython(set_relation_defaults, reverse_func),
        migrations.AlterField(
            model_name="relation",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="metadata.system",
            ),
        ),
        migrations.AlterField(
            model_name="classifier",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
