# Generated by Django 5.0.2 on 2024-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0005_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
