# Generated by Django 5.0.2 on 2024-07-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0006_interface_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metadata.classifier",
            ),
        ),
    ]
