# Generated by Django 5.0.2 on 2024-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0009_release_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="release_notes",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
