# Generated by Django 5.0.2 on 2025-11-10 13:27

import django.db.models.deletion
from django.db import migrations, models


def forwards_fill_project(apps, schem_editor):
    Classifier = apps.get_model("metadata", "Classifier")
    System = apps.get_model("metadata", "System")

    for cls in Classifier.objects.all():
        # Get project id from system
        if cls.system_id:
            try:
                system = System.objects.get(id=cls.system_id)
                cls.project_id = system.project_id
                cls.save(update_fields=["project"])
            except System.DoesNotExist:
                pass


def backwards_unset_project(apps, schema_editor):
    Classifier = apps.get_model("metadata", "Classifier")
    Classifier.objects.update(project_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0010_release_release_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.project",
            ),
        ),
        migrations.AlterField(
            model_name="classifier",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.system",
            ),
        ),
        migrations.RunPython(forwards_fill_project, backwards_unset_project),
        migrations.AddField(
            model_name="classifier",
            name="project",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.project",
            ),
        ),
    ]
