# Generated by Django 5.0.2 on 2025-11-10 13:27

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0010_release_release_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifier",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.system",
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.project",
            ),
        ),
    ]
