# Generated by Django 5.0.2 on 2026-03-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0011_classifier_project_alter_classifier_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="diagrams",
        ),
        migrations.RemoveField(
            model_name="release",
            name="interfaces",
        ),
        migrations.RemoveField(
            model_name="release",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="release",
            name="system",
        ),
        migrations.AddField(
            model_name="release",
            name="project_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="interface",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interfaces",
                to="metadata.system",
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="metadata.project",
            ),
        ),
        migrations.AddField(
            model_name="classifier",
            name="original_system_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
