# Generated by Django 5.0.2 on 2026-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0012_remove_release_diagrams_remove_release_interfaces_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="original_system_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
