# Generated by Django 5.0.1 on 2024-01-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classifier",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("type", models.CharField()),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
                ("type", models.CharField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="metadata.classifier",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="metadata.classifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classifier",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadata.system"
            ),
        ),
    ]
