# Generated by Django 5.0.1 on 2024-01-29 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metadata",
            "0002_relation_system_alter_classifier_id_alter_project_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classifier",
            name="type",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="type",
        ),
    ]
