# Generated by Django 5.0.1 on 2024-01-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0003_remove_classifier_type_remove_relation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifier",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifiers",
                to="metadata.system",
            ),
        ),
    ]
