FROM node:18-alpine
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install --frozen-lockfile
ENV NODE_OPTIONS=--max-old-space-size=1536
RUN apk add --no-cache nginx && mkdir -p /usr/share/nginx/html
COPY nginx.cloud.conf /etc/nginx/http.d/default.conf
CMD ["sh", "-c", "npm run build && cp -r /usr/src/app/dist/* /usr/share/nginx/html/ && exec nginx -g 'daemon off;'"]
