FROM node:18.20.8-alpine3.20 AS builder
WORKDIR /usr/src/app
COPY --chown=node:node package.json package-lock.json ./
USER node
RUN npm ci
ENV NODE_OPTIONS=--max-old-space-size=1536
COPY --chown=node:node index.html postcss.config.js tailwind.config.js tsconfig.json tsconfig.node.json vite.config.ts vitest.config.ts ./
COPY --chown=node:node public ./public
COPY --chown=node:node src ./src
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine
COPY nginx.cloud.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html/
CMD ["nginx", "-g", "daemon off;"]
