version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:
    image: postgres
    env_file: config/postgres.env
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  studio-api:
    depends_on: ['postgres']
    build:
      context: model
    env_file: config/model.env
    volumes:
      - ./model/model:/usr/src/model:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio-api.rule=Host(`api.ai4mde.localhost`)"
      - "traefik.http.routers.studio-api.entrypoints=web"
      - "traefik.http.services.studio-api.loadbalancer.server.port=8000"

  studio:
    build:
      context: studio
    env_file: config/studio.env
    volumes:
      - ./studio/src:/usr/src/app/src:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(`ai4mde.localhost`)"
      - "traefik.http.routers.studio.entrypoints=web"
      - "traefik.http.services.studio.loadbalancer.server.port=5173"

volumes:
  pgsql-data: