# Generated by Django 5.0.1 on 2024-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prose", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="step",
            field=models.SmallIntegerField(default=0),
        ),
    ]
