# Generated by Django 5.0.2 on 2024-07-15 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metadata", "0006_interface_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prototype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("running", models.BooleanField(default=False)),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("container_url", models.URLField(blank=True, null=True)),
                ("container_port", models.IntegerField(blank=True, null=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.system",
                    ),
                ),
            ],
        ),
    ]
