# Generated by Django 5.0.2 on 2024-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prototype",
            old_name="container_port",
            new_name="port",
        ),
        migrations.RemoveField(
            model_name="prototype",
            name="container_id",
        ),
        migrations.RemoveField(
            model_name="prototype",
            name="container_url",
        ),
    ]
