# Generated by Django 5.0.2 on 2024-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_rename_container_port_prototype_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prototype",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
