# Generated by Django 5.0.2 on 2024-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0003_prototype_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prototype",
            name="port",
        ),
        migrations.RemoveField(
            model_name="prototype",
            name="running",
        ),
        migrations.AddField(
            model_name="prototype",
            name="database_hash",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
