# Generated by Django 5.0.1 on 2024-01-30 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requirements", models.TextField(default="")),
                ("output", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(default="metadata", max_length=100)),
                (
                    "url",
                    models.CharField(
                        default="http://tiantian-class.ai4mde-prose.localhost/",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
