"""
Multi-candidate activity generation via repeated LLM calls.

Overview
--------
This module implements multi-candidate generation by repeatedly
calling `model_activity` with the same input.

It is not part of the baseline pipeline and is for AI-assisted workflows where multiple candidate models are generated (e.g., for human selection).
"""
from typing import List

from .refinement_generator import model_activity


def generate_multiple_models(process_text: str, num_models: int = 3) -> List[dict]:
    """
Generate multiple candidate activity models for the same process.

Overview
--------
Produces several independent activity diagram by repeatedly calling
`model_activity`. Each call generates one candidate model.

Behavior
--------
- Each candidate is generated by calling the LLM separately.
- This ensures diversity across candidates.

Parameters
----------
process_text : str
    Natural language description of the process.

num_models : int, default=3
    Number of candidate models to generate.

Returns
-------
List[dict]
    A list of validated activity diagram, where each element has
    the structure:
    {
        "nodes": [...],
        "edges": [...]
    }
"""
    if num_models <= 0:
        return []

    models: List[dict] = []
    for _ in range(num_models):
        model = model_activity(process_text=process_text)
        models.append(model)
    return models
