# Generated by Django 5.0.2 on 2024-10-07 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metadata", "0007_interface_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SRSDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=8)),
                ("description", models.TextField()),
                ("path", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.project",
                    ),
                ),
            ],
        ),
    ]
