# Generated by Django 5.0.2 on 2026-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagram",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diagram",
            name="name",
            field=models.CharField(default="Diagram", max_length=200),
        ),
    ]
