# Generated by Django 5.0.1 on 2024-01-29 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagram", "0001_initial"),
        (
            "metadata",
            "0002_relation_system_alter_classifier_id_alter_project_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagram",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="diagram",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagrams",
                to="metadata.system",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="diagram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="diagram.diagram",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="diagram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="diagram.diagram",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
