# Generated by Django 5.0.2 on 2024-10-07 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metadata", "0007_interface_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("chat", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
