import {
    ActionNode,
    ActorNode,
    ClassNode,
    ClassifierNode,
    ComponentNode,
    DecisionNode,
    EnumNode,
    EventNode,
    FinalNode,
    ForkNode,
    InitialNode,
    JoinNode,
    MergeNode,
    ObjectNode,
    PostconditionNode,
    PreconditionNode,
    ScenarioNode,
    SwimlaneGroupNode,
    SystemBoundaryNode,
    TriggerNode,
    UsecaseNode,
} from "$diagram/components/nodes";
import { NodeTypes } from "reactflow";
import { FallbackNode } from "./FallbackNode";

export const nodeTypes: NodeTypes = {
    class: ClassNode,
    enum: EnumNode,
    signal: ClassifierNode,
    container: ComponentNode,
    component: ComponentNode,
    system: ComponentNode,
    interface: ClassifierNode,
    action: ActionNode,
    initial: InitialNode,
    decision: DecisionNode,
    merge: MergeNode,
    fork: ForkNode,
    join: JoinNode,
    final: FinalNode,
    object: ObjectNode,
    event: EventNode,
    actor: ActorNode,
    postcondition: PostconditionNode,
    precondition: PreconditionNode,
    scenario: ScenarioNode,
    trigger: TriggerNode,
    usecase: UsecaseNode,
    default: FallbackNode,
    swimlanegroup: SwimlaneGroupNode,
    system_boundary: SystemBoundaryNode,
};
