version: "3.3"

services:
  tiantian-class:
    build:
      context: metadata/tiantian-class
    networks:
      - ai4mde_traefik
    environment:
      - "CORENLP_URL=https://corenlp.semax.nguml.com"
    volumes:
      - "./metadata/tiantian-class/src:/usr/src/app/src:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tiantian-class.rule=Host(`tiantian-class.ai4mde-prose.localhost`)"
      - "traefik.http.routers.tiantian-class.entrypoints=web"
      - "traefik.http.services.tiantian-class.loadbalancer.server.port=8000"

networks:
  ai4mde_traefik:
    name: "ai4mde_traefik"
    external: true # TODO: document this uses the studio traefik network (see studio/docker-compose.yml)
